/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sirsaugsage (https://sketchfab.com/sirsausage)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-game-inn-192bf30a7e28425ab385aef19769d4b0
Title: Fantasy Game Inn
*/

import { useGLTF } from "@react-three/drei"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    TheInn_bakeInn_0: THREE.Mesh
  }
  materials: {
    bakeInn: THREE.MeshBasicMaterial
  }
}

export function Map(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/fantasy_game_inn.glb") as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.099}>
        <group>
          <mesh castShadow receiveShadow geometry={nodes.TheInn_bakeInn_0.geometry} material={materials.bakeInn} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/fantasy_game_inn.glb")
