/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei"
import { RigidBody } from "@react-three/rapier"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    Cube000_0: THREE.Mesh
    Cube001_0: THREE.Mesh
    Cube002_0: THREE.Mesh
    Cube009_0: THREE.Mesh
    Cube010_0: THREE.Mesh
    Cube011_0: THREE.Mesh
    Cube013_0: THREE.Mesh
    Cube014_0: THREE.Mesh
    Cylinder000_0: THREE.Mesh
    Cylinder001_0: THREE.Mesh
    Plane_0: THREE.Mesh
    Plane000_0: THREE.Mesh
    Plane001_0: THREE.Mesh
    Plane002_0: THREE.Mesh
    Plane003_0: THREE.Mesh
    Plane004_0: THREE.Mesh
    Plane005_0: THREE.Mesh
    Plane006_0: THREE.Mesh
    Plane007_0: THREE.Mesh
    Plane008_0: THREE.Mesh
    Sphere001_0: THREE.Mesh
    Text001_0: THREE.Mesh
  }
  materials: {
    ["material_3.001"]: THREE.MeshStandardMaterial
    ["material_10.001"]: THREE.MeshStandardMaterial
    ["material_9.001"]: THREE.MeshStandardMaterial
    ["material_14.001"]: THREE.MeshPhysicalMaterial
    ["material_13.001"]: THREE.MeshStandardMaterial
    ["material_7.001"]: THREE.MeshStandardMaterial
    ["material_2.001"]: THREE.MeshStandardMaterial
    ["material_5.001"]: THREE.MeshStandardMaterial
    ["material_11.001"]: THREE.MeshStandardMaterial
    ["material_1.001"]: THREE.MeshStandardMaterial
    ["material_12.001"]: THREE.MeshStandardMaterial
    ["material_6.001"]: THREE.MeshStandardMaterial
    ["material.001"]: THREE.MeshStandardMaterial
    ["material_4.001"]: THREE.MeshStandardMaterial
    ["material_8.001"]: THREE.MeshStandardMaterial
  }
}

export function Map(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/unti333tled.glb") as GLTFResult
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null} position={[4, 0, 8]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube000_0.geometry}
            material={materials["material_3.001"]}
            position={[2.229, -0.264, 0.531]}
            rotation={[0, 0, -3.007]}
            scale={[0.555, 0.769, 0.555]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_0.geometry}
            material={materials["material_3.001"]}
            position={[1.979, 1.59, 0.531]}
            scale={[0.555, 0.769, 0.555]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_0.geometry}
            material={materials["material_3.001"]}
            position={[2.143, 0.707, 1.629]}
            rotation={[Math.PI, 0, 0.135]}
            scale={[0.555, 0.769, 0.555]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_0.geometry}
            material={materials["material_10.001"]}
            position={[15.083, -1.572, 0.514]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_0.geometry}
            material={materials["material_9.001"]}
            position={[7.771, -1.572, 0.335]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_0.geometry}
            material={materials["material_14.001"]}
            position={[5.607, 12.989, 4.098]}
            rotation={[-0.02, -0.01, 0.822]}
            scale={[0.255, 0.255, 0.197]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_0.geometry}
            material={materials["material_13.001"]}
            position={[0.855, 18.169, 3.04]}
            rotation={[0, 0, Math.PI / 2]}
            scale={0.958}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_0.geometry}
            material={materials["material_7.001"]}
            position={[-5.171, 9.111, 15.446]}
            scale={0.098}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder000_0.geometry}
            material={materials["material_2.001"]}
            position={[3.86, 18.232, -0.045]}
            rotation={[0.113, -0.109, 0.605]}
            scale={0.128}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_0.geometry}
            material={materials["material_2.001"]}
            position={[5.179, 19.738, 0.222]}
            rotation={[0, 0, -1.191]}
            scale={0.128}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_0.geometry}
            material={materials["material_5.001"]}
            position={[11.668, -0.832, -0.036]}
            rotation={[0, 0, 1.257]}
            scale={0.697}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane000_0.geometry}
            material={materials["material_11.001"]}
            position={[5.072, 23.401, 11.792]}
            rotation={[-0.482, 0.203, 1.203]}
            scale={0.389}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_0.geometry}
            material={materials["material_1.001"]}
            position={[16.64, 17.942, 0.928]}
            rotation={[0.14, -0.044, -0.524]}
            scale={0.454}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_0.geometry}
            material={materials["material_12.001"]}
            position={[0, 0, 0.397]}
            scale={27.971}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_0.geometry}
            material={materials["material_1.001"]}
            position={[18.719, 18.328, 0.938]}
            rotation={[0, 0, -2.858]}
            scale={0.454}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004_0.geometry}
            material={materials["material_1.001"]}
            position={[-1.193, -2.663, 1.307]}
            rotation={[0, 0, -1.605]}
            scale={0.266}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005_0.geometry}
            material={materials["material_6.001"]}
            position={[-11.175, 25.238, 5.745]}
            rotation={[Math.PI / 2, -1.002, 0]}
            scale={[1.304, 2.024, 1.304]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_0.geometry}
            material={materials["material.001"]}
            position={[19.13, 13.384, 2.096]}
            rotation={[1.582, -0.408, 2.158]}
            scale={0.048}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_0.geometry}
            material={materials["material.001"]}
            position={[2.934, -3.629, 2.253]}
            rotation={[-1.555, 0.633, -0.974]}
            scale={0.048}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008_0.geometry}
            material={materials["material.001"]}
            position={[12.773, 10.98, 2.095]}
            rotation={[-1.346, -1.198, -0.769]}
            scale={0.048}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere001_0.geometry}
            material={materials["material_4.001"]}
            position={[12.24, 20.064, 0.699]}
            rotation={[-Math.PI / 2, 0, -1.379]}
            scale={1.042}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Text001_0.geometry}
            material={materials["material_8.001"]}
            position={[20.013, 7.23, 5.606]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
      </group>
    </RigidBody>
  )
}

useGLTF.preload("/unti333tled.glb")
