/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei"
import { RigidBody } from "@react-three/rapier"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    mesh1278426877: THREE.Mesh
    mesh1278426877_1: THREE.Mesh
    mesh1521680610: THREE.Mesh
    mesh1521680610_1: THREE.Mesh
    mesh83168110: THREE.Mesh
    mesh83168110_1: THREE.Mesh
    mesh334523194: THREE.Mesh
    mesh334523194_1: THREE.Mesh
    group1624869655: THREE.Mesh
    mesh333484390: THREE.Mesh
    mesh333484390_1: THREE.Mesh
    mesh434737554: THREE.Mesh
    mesh434737554_1: THREE.Mesh
    mesh587842124: THREE.Mesh
    mesh587842124_1: THREE.Mesh
    mesh670963560: THREE.Mesh
    mesh670963560_1: THREE.Mesh
    mesh628219677: THREE.Mesh
    mesh628219677_1: THREE.Mesh
    mesh1761245136: THREE.Mesh
    mesh1761245136_1: THREE.Mesh
    mesh893102471: THREE.Mesh
    mesh893102471_1: THREE.Mesh
    mesh1614041323: THREE.Mesh
    mesh1614041323_1: THREE.Mesh
    mesh1832268957: THREE.Mesh
    mesh1832268957_1: THREE.Mesh
    group1300204801: THREE.Mesh
    mesh889829741: THREE.Mesh
    mesh889829741_1: THREE.Mesh
    mesh448284131: THREE.Mesh
    mesh448284131_1: THREE.Mesh
    mesh448284131_2: THREE.Mesh
    mesh2147124318: THREE.Mesh
    mesh2147124318_1: THREE.Mesh
    mesh2147124318_2: THREE.Mesh
    group1319867724: THREE.Mesh
    mesh2088875034: THREE.Mesh
    mesh2088875034_1: THREE.Mesh
    mesh1552020564: THREE.Mesh
    mesh1552020564_1: THREE.Mesh
    mesh2018269649: THREE.Mesh
    mesh2018269649_1: THREE.Mesh
    mesh754051893: THREE.Mesh
    mesh754051893_1: THREE.Mesh
    group1649958311: THREE.Mesh
    group1542202684: THREE.Mesh
    group2024610251: THREE.Mesh
    group106633305: THREE.Mesh
    group1617579958: THREE.Mesh
    mesh1259796184: THREE.Mesh
    mesh1259796184_1: THREE.Mesh
    mesh1532021637: THREE.Mesh
    mesh1532021637_1: THREE.Mesh
    group1031994445: THREE.Mesh
    group1927682795: THREE.Mesh
    mesh732610831: THREE.Mesh
    mesh732610831_1: THREE.Mesh
    group954551664: THREE.Mesh
    group380478114: THREE.Mesh
    group1020755941: THREE.Mesh
    mesh10206897: THREE.Mesh
    mesh10206897_1: THREE.Mesh
    mesh425028400: THREE.Mesh
    mesh425028400_1: THREE.Mesh
    group570844934: THREE.Mesh
    group297236692: THREE.Mesh
    group1981551001: THREE.Mesh
    mesh1573009976: THREE.Mesh
    mesh1573009976_1: THREE.Mesh
    group485686738: THREE.Mesh
    group191109532: THREE.Mesh
    group1753322047: THREE.Mesh
    group1599551814: THREE.Mesh
    mesh893143912: THREE.Mesh
    mesh893143912_1: THREE.Mesh
    mesh899160107: THREE.Mesh
    mesh899160107_1: THREE.Mesh
    group1810227383: THREE.Mesh
    group14710984: THREE.Mesh
    group117144341: THREE.Mesh
    group1716582284: THREE.Mesh
    group1199608762: THREE.Mesh
    group1455677288: THREE.Mesh
    group1706704943: THREE.Mesh
    group1431889966: THREE.Mesh
    mesh637662632: THREE.Mesh
    mesh637662632_1: THREE.Mesh
    mesh321329646: THREE.Mesh
    mesh321329646_1: THREE.Mesh
    mesh321329646_2: THREE.Mesh
    mesh2033220094: THREE.Mesh
    mesh2033220094_1: THREE.Mesh
    mesh2033220094_2: THREE.Mesh
    mesh1553100547: THREE.Mesh
    mesh1553100547_1: THREE.Mesh
    group102934799: THREE.Mesh
    group1736740255: THREE.Mesh
    group973897519: THREE.Mesh
    group264293210: THREE.Mesh
    group1816843430: THREE.Mesh
    group935005122: THREE.Mesh
    mesh1100506130: THREE.Mesh
    mesh1100506130_1: THREE.Mesh
    group1589182040: THREE.Mesh
    mesh94757206: THREE.Mesh
    mesh94757206_1: THREE.Mesh
    group996890033: THREE.Mesh
    mesh953372173: THREE.Mesh
    mesh953372173_1: THREE.Mesh
    mesh507856882: THREE.Mesh
    mesh507856882_1: THREE.Mesh
    mesh1805400969: THREE.Mesh
    mesh1805400969_1: THREE.Mesh
    mesh1059548614: THREE.Mesh
    mesh1059548614_1: THREE.Mesh
    group357874894: THREE.Mesh
    group1059759620: THREE.Mesh
    mesh208373541: THREE.Mesh
    mesh208373541_1: THREE.Mesh
    mesh827047037: THREE.Mesh
    mesh827047037_1: THREE.Mesh
    group93576509: THREE.Mesh
    mesh1357876570: THREE.Mesh
    mesh1357876570_1: THREE.Mesh
    group1554940965: THREE.Mesh
    group563748078: THREE.Mesh
    group592672588: THREE.Mesh
    group167485636: THREE.Mesh
    group76996509: THREE.Mesh
    group340322237: THREE.Mesh
    group1730749405: THREE.Mesh
    group141075656: THREE.Mesh
    group676485652: THREE.Mesh
    group1291498314: THREE.Mesh
    group1331050764: THREE.Mesh
    group1737370271: THREE.Mesh
    group1061606081: THREE.Mesh
    group108924459: THREE.Mesh
    group1750064751: THREE.Mesh
    mesh2102152594: THREE.Mesh
    mesh2102152594_1: THREE.Mesh
    mesh2102152594_2: THREE.Mesh
    mesh1019026647: THREE.Mesh
    mesh1019026647_1: THREE.Mesh
    mesh1019026647_2: THREE.Mesh
    mesh1469669843: THREE.Mesh
    mesh1469669843_1: THREE.Mesh
    group1819212380: THREE.Mesh
    group2124851113: THREE.Mesh
    group521776732: THREE.Mesh
    group1727044876: THREE.Mesh
    group1411117821: THREE.Mesh
    group920500871: THREE.Mesh
    group105198330: THREE.Mesh
    group1285918478: THREE.Mesh
    group175688801: THREE.Mesh
    group1441911556: THREE.Mesh
    group1289875547: THREE.Mesh
    group1463837503: THREE.Mesh
    group817123616: THREE.Mesh
    group1604985082: THREE.Mesh
    group849852679: THREE.Mesh
    group2023475740: THREE.Mesh
    group977697981: THREE.Mesh
    group821679922: THREE.Mesh
    group980470848: THREE.Mesh
    group252642479: THREE.Mesh
    group1072940844: THREE.Mesh
    group1662842189: THREE.Mesh
    group1403903072: THREE.Mesh
    mesh2079552935: THREE.Mesh
    mesh2079552935_1: THREE.Mesh
    group471689571: THREE.Mesh
    group322509107: THREE.Mesh
    group1408896138: THREE.Mesh
    group130627608: THREE.Mesh
    mesh1293335248: THREE.Mesh
    mesh1293335248_1: THREE.Mesh
    mesh1281310801: THREE.Mesh
    mesh1281310801_1: THREE.Mesh
    mesh929949656: THREE.Mesh
    mesh929949656_1: THREE.Mesh
    group703967169: THREE.Mesh
    mesh466444879: THREE.Mesh
    mesh466444879_1: THREE.Mesh
    mesh2069834437: THREE.Mesh
    mesh2069834437_1: THREE.Mesh
    mesh1111409910: THREE.Mesh
    mesh1111409910_1: THREE.Mesh
    group823469175: THREE.Mesh
    group695023501: THREE.Mesh
    group1299048157: THREE.Mesh
    group674505503: THREE.Mesh
    group940952375: THREE.Mesh
    mesh1916268289: THREE.Mesh
    mesh1916268289_1: THREE.Mesh
    mesh1710045687: THREE.Mesh
    mesh1710045687_1: THREE.Mesh
    mesh879162085: THREE.Mesh
    mesh879162085_1: THREE.Mesh
    mesh127435197: THREE.Mesh
    mesh127435197_1: THREE.Mesh
    mesh740245345: THREE.Mesh
    mesh740245345_1: THREE.Mesh
    group2043797211: THREE.Mesh
    group2096443621: THREE.Mesh
    group1351501348: THREE.Mesh
    group1296516561: THREE.Mesh
    group1347956074: THREE.Mesh
    group1394359003: THREE.Mesh
    group606706568: THREE.Mesh
    group538829257: THREE.Mesh
    group1079629055: THREE.Mesh
    group2140423805: THREE.Mesh
    group520795728: THREE.Mesh
    group1736027913: THREE.Mesh
    group677167165: THREE.Mesh
    group2059620541: THREE.Mesh
    group2079241732: THREE.Mesh
    group219837237: THREE.Mesh
    group1298066381: THREE.Mesh
    group782535091: THREE.Mesh
    group1972870179: THREE.Mesh
    group1116484277: THREE.Mesh
    group2086494967: THREE.Mesh
    group1605617712: THREE.Mesh
    group202791378: THREE.Mesh
    group224282808: THREE.Mesh
    group1672346489: THREE.Mesh
    group1012714200: THREE.Mesh
    group2021306996: THREE.Mesh
    group1674800908: THREE.Mesh
    group723369535: THREE.Mesh
    group1739260293: THREE.Mesh
    group1968770728: THREE.Mesh
    group929368027: THREE.Mesh
    group1087192299: THREE.Mesh
    group1609322469: THREE.Mesh
    group1844459471: THREE.Mesh
    group1233664824: THREE.Mesh
    group263536445: THREE.Mesh
    group530174538: THREE.Mesh
    group1938458266: THREE.Mesh
    group2143458320: THREE.Mesh
    group335241874: THREE.Mesh
    group1079389307: THREE.Mesh
    group1487852410: THREE.Mesh
    group171653077: THREE.Mesh
    group1218822519: THREE.Mesh
    group1922779379: THREE.Mesh
    group972428242: THREE.Mesh
    group2080918788: THREE.Mesh
    group702372666: THREE.Mesh
    group1918849253: THREE.Mesh
    group337042894: THREE.Mesh
    group1307981817: THREE.Mesh
    group1768835634: THREE.Mesh
    group1087123104: THREE.Mesh
    mesh1062168222: THREE.Mesh
    mesh1062168222_1: THREE.Mesh
    group1485689576: THREE.Mesh
    group1672303532: THREE.Mesh
    group1451070174: THREE.Mesh
    group973028330: THREE.Mesh
    group1914452461: THREE.Mesh
    mesh541350193: THREE.Mesh
    mesh541350193_1: THREE.Mesh
    group1422008037: THREE.Mesh
    group1716486804: THREE.Mesh
    group1982093830: THREE.Mesh
    group1074018142: THREE.Mesh
    group2072218333: THREE.Mesh
    group339860232: THREE.Mesh
    group1309577048: THREE.Mesh
    group2092067519: THREE.Mesh
    group406181547: THREE.Mesh
    group1812623347: THREE.Mesh
    group1974005764: THREE.Mesh
    group1395752637: THREE.Mesh
    group600364694: THREE.Mesh
    group1367132916: THREE.Mesh
    group906349452: THREE.Mesh
    group1949399061: THREE.Mesh
    group678409134: THREE.Mesh
    group1569785622: THREE.Mesh
    group1977132996: THREE.Mesh
    group1206612008: THREE.Mesh
    mesh441143647: THREE.Mesh
    mesh441143647_1: THREE.Mesh
    mesh441143647_2: THREE.Mesh
    mesh441143647_3: THREE.Mesh
    mesh441143647_4: THREE.Mesh
    mesh441143647_5: THREE.Mesh
    mesh441143647_6: THREE.Mesh
    mesh441143647_7: THREE.Mesh
    mesh441143647_8: THREE.Mesh
    mesh441143647_9: THREE.Mesh
    mesh441143647_10: THREE.Mesh
    mesh441143647_11: THREE.Mesh
    mesh441143647_12: THREE.Mesh
    mesh441143647_13: THREE.Mesh
    mesh441143647_14: THREE.Mesh
    mesh441143647_15: THREE.Mesh
    mesh441143647_16: THREE.Mesh
    group2140606217: THREE.Mesh
    group1181315615: THREE.Mesh
    group1933103409: THREE.Mesh
    group1665044243: THREE.Mesh
    mesh211273111: THREE.Mesh
    mesh211273111_1: THREE.Mesh
    mesh211273111_2: THREE.Mesh
    mesh211273111_3: THREE.Mesh
    group1164842516: THREE.Mesh
    group813903427: THREE.Mesh
    group1594730018: THREE.Mesh
    group1702486614: THREE.Mesh
    group784608724: THREE.Mesh
    group456469304: THREE.Mesh
    mesh754699406: THREE.Mesh
    mesh754699406_1: THREE.Mesh
    group1964951859: THREE.Mesh
    group1474369921: THREE.Mesh
    group1688306527: THREE.Mesh
    group510356646: THREE.Mesh
    group1340029215: THREE.Mesh
    group597475406: THREE.Mesh
    group1829971493: THREE.Mesh
    group442249448: THREE.Mesh
    group39064670: THREE.Mesh
    group580780337: THREE.Mesh
    group173335761: THREE.Mesh
    group953656139: THREE.Mesh
    group1176856593: THREE.Mesh
    group657660096: THREE.Mesh
    group1979975046: THREE.Mesh
    mesh1912095068: THREE.Mesh
    mesh1912095068_1: THREE.Mesh
    group1228742028: THREE.Mesh
    group664066781: THREE.Mesh
    mesh662027773: THREE.Mesh
    mesh662027773_1: THREE.Mesh
    group1145163629: THREE.Mesh
    group1868896045: THREE.Mesh
    group158448036: THREE.Mesh
    mesh1714428766: THREE.Mesh
    mesh1714428766_1: THREE.Mesh
    mesh1714428766_2: THREE.Mesh
    mesh392228261: THREE.Mesh
    mesh392228261_1: THREE.Mesh
    group1792037854: THREE.Mesh
    group1122924605: THREE.Mesh
    mesh1376546335: THREE.Mesh
    mesh1376546335_1: THREE.Mesh
    mesh1728563831: THREE.Mesh
    mesh1728563831_1: THREE.Mesh
    mesh1853124575: THREE.Mesh
    mesh1853124575_1: THREE.Mesh
    mesh1996825778: THREE.Mesh
    mesh1996825778_1: THREE.Mesh
    mesh1242177559: THREE.Mesh
    mesh1242177559_1: THREE.Mesh
    mesh617580806: THREE.Mesh
    mesh617580806_1: THREE.Mesh
    mesh1371359911: THREE.Mesh
    mesh1371359911_1: THREE.Mesh
    mesh1638077688: THREE.Mesh
    mesh1638077688_1: THREE.Mesh
    mesh664516908: THREE.Mesh
    mesh664516908_1: THREE.Mesh
    mesh1546854837: THREE.Mesh
    mesh1546854837_1: THREE.Mesh
    mesh391413127: THREE.Mesh
    mesh391413127_1: THREE.Mesh
    mesh1918007228: THREE.Mesh
    mesh1918007228_1: THREE.Mesh
    mesh1794901471: THREE.Mesh
    mesh1794901471_1: THREE.Mesh
    mesh1794901471_2: THREE.Mesh
    mesh1794901471_3: THREE.Mesh
    mesh1085366757: THREE.Mesh
    mesh1085366757_1: THREE.Mesh
    mesh1085366757_2: THREE.Mesh
    mesh1085366757_3: THREE.Mesh
    mesh726275562: THREE.Mesh
    mesh726275562_1: THREE.Mesh
    mesh726275562_2: THREE.Mesh
    mesh726275562_3: THREE.Mesh
  }
  materials: {
    mat18: THREE.MeshStandardMaterial
    mat21: THREE.MeshStandardMaterial
    mat19: THREE.MeshStandardMaterial
    mat17: THREE.MeshStandardMaterial
    mat16: THREE.MeshStandardMaterial
    mat15: THREE.MeshStandardMaterial
    mat22: THREE.MeshStandardMaterial
    mat20: THREE.MeshStandardMaterial
    mat24: THREE.MeshStandardMaterial
    mat23: THREE.MeshStandardMaterial
    mat3: THREE.MeshStandardMaterial
    mat2: THREE.MeshStandardMaterial
    mat5: THREE.MeshStandardMaterial
    mat10: THREE.MeshStandardMaterial
    mat7: THREE.MeshStandardMaterial
    mat1: THREE.MeshStandardMaterial
    mat25: THREE.MeshStandardMaterial
    mat6: THREE.MeshStandardMaterial
    mat8: THREE.MeshStandardMaterial
    mat0: THREE.MeshStandardMaterial
  }
}

export function House(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/house.glb") as GLTFResult
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} scale={[3.2, 3.2, 3.2]} position={[3.2, 0, 3.2]} dispose={null}>
        <mesh castShadow receiveShadow geometry={nodes.group1624869655.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1300204801.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1319867724.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1649958311.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1542202684.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group2024610251.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group106633305.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1617579958.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1031994445.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1927682795.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group954551664.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group380478114.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1020755941.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group570844934.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group297236692.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1981551001.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group485686738.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group191109532.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1753322047.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1599551814.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1810227383.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group14710984.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.group117144341.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.group1716582284.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1199608762.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1455677288.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1706704943.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1431889966.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group102934799.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1736740255.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group973897519.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group264293210.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1816843430.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group935005122.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1589182040.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.group996890033.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group357874894.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1059759620.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group93576509.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1554940965.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.group563748078.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.group592672588.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.group167485636.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.group76996509.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group340322237.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1730749405.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group141075656.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group676485652.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1291498314.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1331050764.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1737370271.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1061606081.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group108924459.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1750064751.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1819212380.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group2124851113.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group521776732.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1727044876.geometry} material={materials.mat24} />
        <mesh castShadow receiveShadow geometry={nodes.group1411117821.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group920500871.geometry} material={materials.mat24} />
        <mesh castShadow receiveShadow geometry={nodes.group105198330.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1285918478.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group175688801.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1441911556.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1289875547.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1463837503.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group817123616.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1604985082.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group849852679.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group2023475740.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group977697981.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group821679922.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group980470848.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group252642479.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1072940844.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1662842189.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1403903072.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.group471689571.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group322509107.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1408896138.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group130627608.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group703967169.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.group823469175.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group695023501.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1299048157.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.group674505503.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.group940952375.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.group2043797211.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group2096443621.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1351501348.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1296516561.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1347956074.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1394359003.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group606706568.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group538829257.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1079629055.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group2140423805.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group520795728.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1736027913.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group677167165.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group2059620541.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group2079241732.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group219837237.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1298066381.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group782535091.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1972870179.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1116484277.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group2086494967.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1605617712.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group202791378.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group224282808.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1672346489.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1012714200.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group2021306996.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1674800908.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group723369535.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1739260293.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1968770728.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group929368027.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1087192299.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1609322469.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1844459471.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1233664824.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group263536445.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group530174538.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group1938458266.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group2143458320.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group335241874.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1079389307.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1487852410.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group171653077.geometry} material={materials.mat23} />
        <mesh castShadow receiveShadow geometry={nodes.group1218822519.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1922779379.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group972428242.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group2080918788.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group702372666.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1918849253.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group337042894.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1307981817.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1768835634.geometry} material={materials.mat23} />
        <mesh castShadow receiveShadow geometry={nodes.group1087123104.geometry} material={materials.mat23} />
        <mesh castShadow receiveShadow geometry={nodes.group1485689576.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1672303532.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1451070174.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group973028330.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1914452461.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1422008037.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1716486804.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group1982093830.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group1074018142.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group2072218333.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group339860232.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1309577048.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group2092067519.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group406181547.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1812623347.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.group1974005764.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1395752637.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group600364694.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1367132916.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group906349452.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.group1949399061.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group678409134.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group1569785622.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group1977132996.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group1206612008.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.group2140606217.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1181315615.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1933103409.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1665044243.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1164842516.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group813903427.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1594730018.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1702486614.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group784608724.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group456469304.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1964951859.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1474369921.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1688306527.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group510356646.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1340029215.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group597475406.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1829971493.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group442249448.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group39064670.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group580780337.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group173335761.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group953656139.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1176856593.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group657660096.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1979975046.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1228742028.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group664066781.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1145163629.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1868896045.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group158448036.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1792037854.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.group1122924605.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1278426877.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1278426877_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1521680610.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1521680610_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh83168110.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh83168110_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh334523194.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh334523194_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh333484390.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh333484390_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh434737554.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh434737554_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh587842124.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh587842124_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh670963560.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh670963560_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh628219677.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh628219677_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1761245136.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1761245136_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh893102471.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh893102471_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1614041323.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1614041323_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1832268957.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1832268957_1.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.mesh889829741.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh889829741_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh448284131.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh448284131_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh448284131_2.geometry} material={materials.mat16} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2147124318.geometry} material={materials.mat16} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2147124318_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2147124318_2.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2088875034.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2088875034_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1552020564.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1552020564_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2018269649.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2018269649_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh754051893.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh754051893_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1259796184.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1259796184_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1532021637.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1532021637_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh732610831.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh732610831_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh10206897.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh10206897_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh425028400.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh425028400_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1573009976.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1573009976_1.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.mesh893143912.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh893143912_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh899160107.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh899160107_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh637662632.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh637662632_1.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.mesh321329646.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.mesh321329646_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh321329646_2.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2033220094.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2033220094_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2033220094_2.geometry} material={materials.mat16} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1553100547.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1553100547_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1100506130.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1100506130_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh94757206.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh94757206_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh953372173.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh953372173_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh507856882.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh507856882_1.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1805400969.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1805400969_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1059548614.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1059548614_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh208373541.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh208373541_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh827047037.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh827047037_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1357876570.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1357876570_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2102152594.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2102152594_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2102152594_2.geometry} material={materials.mat16} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1019026647.geometry} material={materials.mat16} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1019026647_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1019026647_2.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1469669843.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1469669843_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2079552935.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2079552935_1.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1293335248.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1293335248_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1281310801.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1281310801_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh929949656.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh929949656_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh466444879.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh466444879_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2069834437.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh2069834437_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1111409910.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1111409910_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1916268289.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1916268289_1.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1710045687.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1710045687_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh879162085.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.mesh879162085_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh127435197.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.mesh127435197_1.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh740245345.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.mesh740245345_1.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1062168222.geometry} material={materials.mat23} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1062168222_1.geometry} material={materials.mat3} />
        <mesh castShadow receiveShadow geometry={nodes.mesh541350193.geometry} material={materials.mat2} />
        <mesh castShadow receiveShadow geometry={nodes.mesh541350193_1.geometry} material={materials.mat5} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_1.geometry} material={materials.mat23} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_2.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_3.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_4.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_5.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_6.geometry} material={materials.mat24} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_7.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_8.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_9.geometry} material={materials.mat10} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_10.geometry} material={materials.mat7} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_11.geometry} material={materials.mat1} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_12.geometry} material={materials.mat25} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_13.geometry} material={materials.mat6} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_14.geometry} material={materials.mat8} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_15.geometry} material={materials.mat0} />
        <mesh castShadow receiveShadow geometry={nodes.mesh441143647_16.geometry} material={materials.mat16} />
        <mesh castShadow receiveShadow geometry={nodes.mesh211273111.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh211273111_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh211273111_2.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh211273111_3.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh754699406.geometry} material={materials.mat21} />
        <mesh castShadow receiveShadow geometry={nodes.mesh754699406_1.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1912095068.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1912095068_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh662027773.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh662027773_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1714428766.geometry} material={materials.mat15} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1714428766_1.geometry} material={materials.mat22} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1714428766_2.geometry} material={materials.mat16} />
        <mesh castShadow receiveShadow geometry={nodes.mesh392228261.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh392228261_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1376546335.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1376546335_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1728563831.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1728563831_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1853124575.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1853124575_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1996825778.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1996825778_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1242177559.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1242177559_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh617580806.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh617580806_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1371359911.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1371359911_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1638077688.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1638077688_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh664516908.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh664516908_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1546854837.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1546854837_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh391413127.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh391413127_1.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1918007228.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1918007228_1.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1794901471.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1794901471_1.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1794901471_2.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1794901471_3.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1085366757.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1085366757_1.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1085366757_2.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh1085366757_3.geometry} material={materials.mat18} />
        <mesh castShadow receiveShadow geometry={nodes.mesh726275562.geometry} material={materials.mat20} />
        <mesh castShadow receiveShadow geometry={nodes.mesh726275562_1.geometry} material={materials.mat17} />
        <mesh castShadow receiveShadow geometry={nodes.mesh726275562_2.geometry} material={materials.mat19} />
        <mesh castShadow receiveShadow geometry={nodes.mesh726275562_3.geometry} material={materials.mat18} />
      </group>
    </RigidBody>
  )
}

useGLTF.preload("/house.glb")
